// Mock data for Trainer Panel prototype

const MOCK_CLIENTS = [
  {
    id: "c1",
    full_name: "Иван Петров",
    email: "ivan.petrov@gmail.com",
    avatar_url: null,
    plan: "pro",
    goal: "Набор мышечной массы",
    weight_kg: 82,
    height_cm: 180,
    fitness_level: "Продвинутый",
    activity: "4–5 раз в неделю",
    equipment: "Штанга, гантели, турник",
    diet: "Без ограничений",
    gender: "М",
    age: 28,
    last_workout_at: "2026-04-20T10:00:00Z",
    total_workouts: 47,
    unread_messages: 3,
    registered_at: "2025-11-14T08:00:00Z",
  },
  {
    id: "c2",
    full_name: "Мария Соколова",
    email: "maria.sokolova@mail.ru",
    avatar_url: null,
    plan: "pro",
    goal: "Похудение",
    weight_kg: 65,
    height_cm: 168,
    fitness_level: "Средний",
    activity: "3 раза в неделю",
    equipment: "Коврик, резинки",
    diet: "Без глютена",
    gender: "Ж",
    age: 32,
    last_workout_at: "2026-04-22T08:30:00Z",
    total_workouts: 31,
    unread_messages: 1,
    registered_at: "2026-01-03T10:00:00Z",
  },
  {
    id: "c3",
    full_name: "Артём Козлов",
    email: "artem.kozlov@yandex.ru",
    avatar_url: null,
    plan: "pro",
    goal: "Поддержание формы",
    weight_kg: 75,
    height_cm: 175,
    fitness_level: "Начинающий",
    activity: "2 раза в неделю",
    equipment: "Гантели",
    diet: "Без ограничений",
    gender: "М",
    age: 24,
    last_workout_at: "2026-04-14T18:00:00Z",
    total_workouts: 12,
    unread_messages: 0,
    registered_at: "2026-03-10T12:00:00Z",
  },
  {
    id: "c4",
    full_name: "Елена Воронова",
    email: "elena.voronova@gmail.com",
    avatar_url: null,
    plan: "pro",
    goal: "Улучшение выносливости",
    weight_kg: 58,
    height_cm: 162,
    fitness_level: "Средний",
    activity: "5 раз в неделю",
    equipment: "Беговая дорожка, велотренажёр",
    diet: "Вегетарианство",
    gender: "Ж",
    age: 35,
    last_workout_at: "2026-04-23T07:00:00Z",
    total_workouts: 88,
    unread_messages: 0,
    registered_at: "2025-09-01T09:00:00Z",
  },
  {
    id: "c5",
    full_name: "Дмитрий Новиков",
    email: "dima.novikov@inbox.ru",
    avatar_url: null,
    plan: "pro",
    goal: "Набор мышечной массы",
    weight_kg: 90,
    height_cm: 183,
    fitness_level: "Продвинутый",
    activity: "6 раз в неделю",
    equipment: "Полный зал",
    diet: "Без ограничений",
    gender: "М",
    age: 26,
    last_workout_at: "2026-04-23T06:30:00Z",
    total_workouts: 134,
    unread_messages: 2,
    registered_at: "2025-07-20T15:00:00Z",
  },
  {
    id: "c6",
    full_name: "Ольга Белова",
    email: "olga.belova@gmail.com",
    avatar_url: null,
    plan: "pro",
    goal: "Реабилитация",
    weight_kg: 70,
    height_cm: 170,
    fitness_level: "Начинающий",
    activity: "2–3 раза в неделю",
    equipment: "Коврик, мяч",
    diet: "Без лактозы",
    gender: "Ж",
    age: 41,
    last_workout_at: "2026-04-09T11:00:00Z",
    total_workouts: 8,
    unread_messages: 0,
    registered_at: "2026-04-01T10:00:00Z",
  },
];

const MOCK_WEIGHT_DATA = {
  c1: [
    { date: "22 янв", weight: 85 }, { date: "29 янв", weight: 84.5 }, { date: "5 фев", weight: 84 },
    { date: "12 фев", weight: 83.5 }, { date: "19 фев", weight: 83 }, { date: "26 фев", weight: 82.8 },
    { date: "5 мар", weight: 82.5 }, { date: "12 мар", weight: 82.3 }, { date: "19 мар", weight: 82.1 },
    { date: "26 мар", weight: 82.4 }, { date: "2 апр", weight: 82.2 }, { date: "9 апр", weight: 82 },
    { date: "16 апр", weight: 81.8 }, { date: "23 апр", weight: 82 },
  ],
  c2: [
    { date: "5 фев", weight: 72 }, { date: "12 фев", weight: 71.2 }, { date: "19 фев", weight: 70.5 },
    { date: "26 фев", weight: 69.8 }, { date: "5 мар", weight: 69 }, { date: "12 мар", weight: 68.5 },
    { date: "19 мар", weight: 68 }, { date: "26 мар", weight: 67.2 }, { date: "2 апр", weight: 66.5 },
    { date: "9 апр", weight: 66 }, { date: "16 апр", weight: 65.5 }, { date: "23 апр", weight: 65 },
  ],
};

const MOCK_WORKOUT_ACTIVITY = {
  c1: [
    { day: "Пн", count: 1 }, { day: "Вт", count: 0 }, { day: "Ср", count: 1 },
    { day: "Чт", count: 1 }, { day: "Пт", count: 0 }, { day: "Сб", count: 1 }, { day: "Вс", count: 0 },
  ],
  c2: [
    { day: "Пн", count: 1 }, { day: "Вт", count: 0 }, { day: "Ср", count: 0 },
    { day: "Чт", count: 1 }, { day: "Пт", count: 0 }, { day: "Сб", count: 1 }, { day: "Вс", count: 0 },
  ],
};

const MOCK_WORKOUTS_LOG = {
  c1: [
    { date: "22 апр 2026", name: "Силовая — верх тела", level: "Продвинутый", points: 30 },
    { date: "20 апр 2026", name: "Грудь и трицепс", level: "Продвинутый", points: 28 },
    { date: "18 апр 2026", name: "Спина и бицепс", level: "Продвинутый", points: 32 },
    { date: "16 апр 2026", name: "Ноги и плечи", level: "Продвинутый", points: 35 },
    { date: "14 апр 2026", name: "Кардио + пресс", level: "Средний", points: 20 },
  ],
  c2: [
    { date: "22 апр 2026", name: "Кардио — интервалы", level: "Средний", points: 25 },
    { date: "20 апр 2026", name: "Пилатес — корпус", level: "Средний", points: 18 },
    { date: "17 апр 2026", name: "Ноги и ягодицы", level: "Средний", points: 22 },
    { date: "15 апр 2026", name: "Растяжка + йога", level: "Начинающий", points: 12 },
  ],
};

const MOCK_MESSAGES = {
  c1: [
    { id: "m1", from: "user", text: "Привет! Хотел спросить про программу на следующую неделю.", time: "14:10", date: "Вчера" },
    { id: "m2", from: "trainer", text: "Привет, Иван! Планирую тебе добавить дополнительный день на ноги. Как восстановление после последней тренировки?", time: "14:25", date: "Вчера" },
    { id: "m3", from: "user", text: "Ноги немного болят, но в целом хорошо. Готов к нагрузке!", time: "14:31", date: "Вчера" },
    { id: "m4", from: "user", text: "Кстати, можешь скинуть видео по технике приседа? Хочу проверить себя.", time: "14:32", date: "Вчера" },
    { id: "m5", from: "trainer", text: "Конечно! Главное — колени не заваливать внутрь, спина прямая, взгляд вперёд. Сегодня назначу новую тренировку с акцентом на технику.", time: "15:00", date: "Вчера" },
    { id: "m6", from: "user", text: "Спасибо! Жду 💪", time: "15:03", date: "Вчера" },
    { id: "m7", from: "user", text: "Доброе утро! Сегодня сделал тренировку — чувствую себя отлично!", time: "09:15", date: "Сегодня" },
    { id: "m8", from: "user", text: "Вес показал 82 кг, продолжаю держаться", time: "09:16", date: "Сегодня" },
    { id: "m9", from: "user", text: "Когда следующее обновление программы?", time: "09:20", date: "Сегодня" },
  ],
  c2: [
    { id: "m1", from: "user", text: "Здравствуйте! Хочу узнать, можно ли заменить кардио на что-то другое?", time: "11:00", date: "Сегодня" },
    { id: "m2", from: "trainer", text: "Привет, Мария! Конечно, можем заменить на плавание или велосипед. Что тебе больше подходит?", time: "11:20", date: "Сегодня" },
    { id: "m3", from: "user", text: "Велосипед на улице — отлично! Спасибо", time: "11:35", date: "Сегодня" },
  ],
  c5: [
    { id: "m1", from: "user", text: "Максим, привет! Как тебе мои результаты за апрель?", time: "08:00", date: "Сегодня" },
    { id: "m2", from: "user", text: "Вес стабильный, жим вырос на 10 кг 🔥", time: "08:01", date: "Сегодня" },
  ],
};

const MOCK_WORKOUTS_LIBRARY = [
  { id: "w1", name: "Силовая — верх тела", type: "Силовая", duration_min: 60, level: "Продвинутый", description: "Жим штанги, тяга блока, разводка гантелей, жим сидя" },
  { id: "w2", name: "Ноги и ягодицы", type: "Силовая", duration_min: 55, level: "Средний", description: "Приседания, выпады, жим ногами, ягодичный мостик" },
  { id: "w3", name: "Кардио — интервалы HIIT", type: "Кардио", duration_min: 30, level: "Средний", description: "Чередование высокой и низкой интенсивности, 8 раундов" },
  { id: "w4", name: "Растяжка и мобильность", type: "Гибкость", duration_min: 40, level: "Начинающий", description: "Растяжка всех групп мышц, суставная гимнастика" },
  { id: "w5", name: "Спина и бицепс", type: "Силовая", duration_min: 50, level: "Продвинутый", description: "Становая тяга, тяга штанги, подтягивания, сгибания на бицепс" },
  { id: "w6", name: "Полное тело — функционал", type: "Функциональная", duration_min: 45, level: "Средний", description: "Берпи, приседания с прыжком, отжимания, скакалка" },
];

Object.assign(window, { MOCK_CLIENTS, MOCK_WEIGHT_DATA, MOCK_WORKOUT_ACTIVITY, MOCK_WORKOUTS_LOG, MOCK_MESSAGES, MOCK_WORKOUTS_LIBRARY });
